services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: penguin
      MYSQL_DATABASE: RetroGameDatabase
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - distributed-network

  api1:
    restart: always
    container_name: api1
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: notifications
      SQL_ROOT: root
      SQL_PASSWORD: penguin
      SQL_PORT: 3306
      DB_HOST: db
      DATABASE: RetroGameDatabase
      API_HOST: 8080
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - distributed-network

  api2:
    restart: always
    container_name: api2
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: notifications
      SQL_ROOT: root
      SQL_PASSWORD: penguin
      SQL_PORT: 3306
      DB_HOST: db
      DATABASE: RetroGameDatabase
      API_HOST: 8080
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - distributed-network

  api3:
    restart: always
    container_name: api3
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: notifications
      SQL_ROOT: root
      SQL_PASSWORD: penguin
      SQL_PORT: 3306
      DB_HOST: db
      DATABASE: RetroGameDatabase
      API_HOST: 8080
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - distributed-network

  auth-api:
    restart: always
    container_name: auth-api
    build:
      context: .
      dockerfile: auth/Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SQL_ROOT: root
      SQL_PASSWORD: penguin
      SQL_PORT: 3306
      DB_HOST: db
      DATABASE: RetroGameDatabase
    depends_on:
      - db
    networks:
      - distributed-network

  nginx:
    restart: always
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api1
      - api2
      - api3
      - auth-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - distributed-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://nginx:80/stub_status"
    depends_on:
      - nginx
    networks:
      - distributed-network

  broker:
    image: apache/kafka:latest
    container_name: broker
    networks:
      - distributed-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"

  email:
    build: ./email
    container_name: email
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: users,offers
      KAFKA_GROUP: email

      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USER: jaime.lindgren@ethereal.email
      SMTP_PASS: 5ugRj4hkejafzrD3Cp
      SMTP_FROM: jaime.lindgren@ethereal.email
    ports:
      - "2112:2112"
    depends_on:
      - broker
    networks:
      - distributed-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - nginx-exporter
      - mysqlExporter
      - kafkaExporter
    networks:
      - distributed-network


  mysqlExporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    command:
      - --mysqld.address=db:3306
      - --mysqld.username=exporter
    environment:
      MYSQLD_EXPORTER_PASSWORD: penguin
    ports:
      - "9104:9104"
    depends_on:
      - db
    networks:
      - distributed-network

  kafkaExporter:
    container_name: kafkaExporter
    image: danielqsj/kafka-exporter:latest
    command:
      - --kafka.server=broker:9092
    ports:
      - "9308:9308"
    depends_on:
      - broker
    networks:
      - distributed-network
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    networks:
      - distributed-network
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  dbdata:
  prometheus_data:
  grafana-storage:


networks:
  distributed-network:
    name: distributed-network



