events {
    worker_connections 1024;
}

http {

    upstream api {
        server api1:8080;
        server api2:8080;
        server api3:8080;
    }


    server {
        listen 80;

        location /stub_status {
            stub_status;
            access_log off;
            allow all;
        }

        location /users/login {
            proxy_pass http://auth-api:8081; # Use your auth-api container name
        }
        

        location /games {
            auth_request /auth-verify; # Check with auth-api first

            # Capture the UserID from auth-api and pass it to the Game API
            auth_request_set $user_id $upstream_http_x_user_id;
            proxy_set_header X-User-ID $user_id;

            proxy_pass http://api;
        }


        location = /auth-verify {
            internal;
            proxy_pass http://auth-api:8081/validate; # Your auth validation endpoint
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

         location / {
                proxy_pass http://api;
         }
    }
}